<?php
/**
 * Nested Sets
 */
return [
    [
        'id' => 1,
        'lft' => 1,
        'rgt' => 12,
        'depth' => 0,
        'name' => 'Root',
        'slug' => 'root',
        'description' => 'This root description',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'status' => 1,
        'meta_description' => 'This root meta-description',
        'meta_keywords' => 'root,test,meta-keywords',
    ],
    [
        'id' => 2,
        'lft' => 2,
        'rgt' => 5,
        'depth' => 1,
        'name' => 'Category 1',
        'slug' => 'category_1',
        'description' => 'This category 1 description',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'status' => 1,
        'meta_description' => 'This category 1 meta-description',
        'meta_keywords' => 'category 1,test,meta-keywords',
    ],
    [
        'id' => 3,
        'lft' => 3,
        'rgt' => 4,
        'depth' => 2,
        'name' => 'Child 1-1',
        'slug' => 'child_1_1',
        'description' => 'This child 1-1 description',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'status' => 1,
        'meta_description' => 'This child 1-1 meta-description',
        'meta_keywords' => 'child,category,test,meta-keywords,1-1',
    ],
    [
        'id' => 4,
        'lft' => 6,
        'rgt' => 11,
        'depth' => 1,
        'name' => 'Category 2',
        'slug' => 'category_2',
        'description' => 'This category 2 description',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'status' => 1,
        'meta_description' => 'This category 2 meta-description',
        'meta_keywords' => 'category 2,test,meta-keywords',
    ],
    [
        'id' => 5,
        'lft' => 7,
        'rgt' => 10,
        'depth' => 2,
        'name' => 'Child 2-1',
        'slug' => 'child_2_1',
        'description' => 'This child 2-1 description',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'status' => 0,
        'meta_description' => 'This child 2-1 meta-description',
        'meta_keywords' => 'child,category,test,meta-keywords,2-1',
    ],
    [
        'id' => 6,
        'lft' => 8,
        'rgt' => 9,
        'depth' => 2,
        'name' => 'Child 2-2',
        'slug' => 'child_2_2',
        'description' => 'This child 2-2 description',
        'created_at' => '1402312317',
        'updated_at' => '1402312317',
        'status' => 1,
        'meta_description' => 'This child 2-2 meta-description',
        'meta_keywords' => 'child,category,test,meta-keywords,2-2',
    ]
];
